# Generated by Django 4.2.15 on 2025-03-24 08:49

import bold_voice.conversations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('type', models.CharField(choices=[('roleplay', 'roleplay'), ('topic', 'topic')], max_length=10, verbose_name='type')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='character name')),
                ('description', models.TextField(help_text='description of the character/persona', verbose_name='character description')),
                ('voice_type', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50, verbose_name='voice type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='character_images/', verbose_name='character image')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('character_role', models.CharField(help_text='the role this character plays in the scenario', max_length=255, verbose_name='character role')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='scenario_icons/', verbose_name='icon')),
                ('gradient_start_color', models.CharField(help_text='hex code of the gradient start color', max_length=7, verbose_name='gradient start color')),
                ('gradient_end_color', models.CharField(help_text='hex code of the gradient end color', max_length=7, verbose_name='gradient end color')),
                ('is_premium', models.BooleanField(default=False, verbose_name='is premium')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='conversations.category', verbose_name='category')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='conversations.character', verbose_name='character')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scenario',
                'verbose_name_plural': 'scenarios',
                'ordering': ['category__sort_order', 'sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='start time')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completion time')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_chats', to='conversations.character', verbose_name='character')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_chats', to='conversations.scenario', verbose_name='scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_chats', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'voice chat',
                'verbose_name_plural': 'voice chats',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('role', models.CharField(choices=[('system', 'system'), ('assistant', 'assistant'), ('user', 'user')], max_length=10, verbose_name='message role')),
                ('audio_file', models.FileField(upload_to=bold_voice.conversations.models.audio_upload_path, verbose_name='audio file')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='transcript')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('voice_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_messages', to='conversations.voicechat', verbose_name='voice chat')),
            ],
            options={
                'verbose_name': 'voice message',
                'verbose_name_plural': 'voice messages',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceMessageScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('score', models.FloatField(default=0, verbose_name='score')),
                ('words', models.JSONField(blank=True, default=list, verbose_name='word scores')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('voice_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_record', to='conversations.voicemessage', verbose_name='voice message')),
            ],
            options={
                'verbose_name': 'voice message score',
                'verbose_name_plural': 'voice message scores',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceChatScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('ai_score', models.FloatField(default=0, verbose_name='ai score')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='feedback')),
                ('num_words_spoken', models.IntegerField(default=0, verbose_name='total words spoken')),
                ('num_perfect_words', models.IntegerField(default=0, verbose_name='correctly pronounced words')),
                ('time_spoken', models.FloatField(default=0.0, verbose_name='duration in seconds')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('voice_chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_record', to='conversations.voicechat', verbose_name='voice chat')),
            ],
            options={
                'verbose_name': 'voice chat score',
                'verbose_name_plural': 'voice chat scores',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
