# Generated by Django 4.2.15 on 2025-03-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicechat',
            name='gradient_end_color',
            field=models.CharField(default='#feb47b', help_text='hex code of the gradient end color', max_length=7, verbose_name='gradient end color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voicechat',
            name='gradient_start_color',
            field=models.CharField(default='#ff7e5f', help_text='hex code of the gradient start color', max_length=7, verbose_name='gradient start color'),
            preserve_default=False,
        ),
    ]
