# Generated by Django 4.2.15 on 2025-04-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_voicechat_gradient_end_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicechatscore',
            name='total_word_score',
            field=models.FloatField(default=0, verbose_name='total word score'),
        ),
    ]
