# Generated by Django 4.2.15 on 2025-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conversations', '0003_voicechatscore_total_word_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'character', 'verbose_name_plural': 'characters'},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'verbose_name': 'scenario', 'verbose_name_plural': 'scenarios'},
        ),
        migrations.AlterModelOptions(
            name='voicechat',
            options={'verbose_name': 'voice chat', 'verbose_name_plural': 'voice chats'},
        ),
        migrations.AlterModelOptions(
            name='voicechatscore',
            options={'verbose_name': 'voice chat score', 'verbose_name_plural': 'voice chat scores'},
        ),
        migrations.AlterModelOptions(
            name='voicemessage',
            options={'verbose_name': 'voice message', 'verbose_name_plural': 'voice messages'},
        ),
        migrations.AlterField(
            model_name='voicechatscore',
            name='num_perfect_words',
            field=models.IntegerField(default=0, verbose_name='total correctly pronounced words'),
        ),
        migrations.AlterField(
            model_name='voicemessagescore',
            name='words',
            field=models.JSONField(blank=True, default=list, verbose_name='words'),
        ),
    ]
