# Generated by Django 4.2.15 on 2025-05-06 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0004_alter_category_options_alter_character_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phoneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('symbol', models.CharField(max_length=25, verbose_name='symbol')),
                ('phonetic', models.CharField(blank=True, max_length=255, null=True, verbose_name='phonetic')),
                ('tip', models.TextField(blank=True, null=True, verbose_name='tip')),
                ('audio_file',
                 models.FileField(blank=True, null=True, upload_to='phonemes/', verbose_name='audio file')),
                ('card_color',
                 models.CharField(help_text='hex code of the card color', max_length=7, verbose_name='card color')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'phoneme',
                'verbose_name_plural': 'phonemes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhonemeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('word', models.CharField(max_length=255, verbose_name='word')),
                ('marks', models.JSONField(blank=True, default=list, verbose_name='marks')),
                ('audio_file',
                 models.FileField(blank=True, null=True, upload_to='phoneme_examples/', verbose_name='audio file')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('phoneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples',
                                              to='conversations.phoneme', verbose_name='phoneme')),
            ],
            options={
                'verbose_name': 'phoneme example',
                'verbose_name_plural': 'phoneme examples',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhonemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('phoneme_type',
                 models.CharField(choices=[('vowel', 'vowel'), ('consonant', 'consonant')], max_length=10,
                                  verbose_name='phoneme type')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'phoneme category',
                'verbose_name_plural': 'phoneme categories',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='phoneme',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phonemes',
                                    to='conversations.phonemecategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='phoneme',
            name='confused_phonemes',
            field=models.ManyToManyField(blank=True, to='conversations.phoneme', verbose_name='confused phonemes'),
        ),
        migrations.AddField(
            model_name='phoneme',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phoneme',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
