# Generated by Django 4.2.15 on 2025-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conversations', '0005_phoneme_phonemeexample_phonemecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemessagescore',
            name='suggested_words',
            field=models.JSONField(blank=True, default=list, verbose_name='suggested words'),
        ),
    ]
