# Generated by Django 4.2.15 on 2025-06-16 12:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0006_voicemessagescore_suggested_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechScanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title',
                 models.CharField(help_text='Configuration title or name', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Description of the configuration', null=True,
                                                 verbose_name='description')),
                ('practice_texts', models.JSONField(blank=True, default=list,
                                                    help_text='List of texts to be used in speech scan sessions',
                                                    verbose_name='practice texts')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active',
                                                  verbose_name='is active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'speech scan configuration',
                'verbose_name_plural': 'speech scan configurations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeechScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('overall_score',
                 models.FloatField(default=0.0, help_text='Average score across all practice texts in this session',
                                   validators=[django.core.validators.MinValueValidator(0.0),
                                               django.core.validators.MaxValueValidator(1.0)],
                                   verbose_name='overall score')),
                ('suggested_words', models.JSONField(blank=True, default=list,
                                                     help_text='list of suggested words for the user to practice',
                                                     verbose_name='suggested words')),
                ('strong_words',
                 models.JSONField(blank=True, default=list, help_text='list of words the user pronounced well',
                                  verbose_name='strong words')),
                ('score_details', models.JSONField(blank=True, default=list,
                                                   help_text='detailed scores for each practice text in the session',
                                                   verbose_name='score details')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('speech_scan_config',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions',
                                   to='conversations.speechscanconfig', verbose_name='speech scan configuration')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_scan_sessions',
                                   to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'speech scan session',
                'verbose_name_plural': 'speech scan sessions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PracticeTextBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('practice_text',
                 models.TextField(help_text='the practice text content', verbose_name='practice text')),
                ('score',
                 models.FloatField(default=0.0, help_text='the score of the practice text', verbose_name='score')),
                ('word_scores', models.JSONField(blank=True, default=list,
                                                 help_text='list of word scores with their status and timing information',
                                                 verbose_name='word scores')),
                ('attempt_count',
                 models.IntegerField(default=0, help_text='the number of times this text has been practiced',
                                     verbose_name='attempt count')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_text_bookmarks',
                                   to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'practice text bookmark',
                'verbose_name_plural': 'practice text bookmarks',
                'abstract': False,
            },
        ),
    ]
