# Generated by Django 4.2.15 on 2025-06-17 06:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0007_speechscanconfig_speechscansession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechscansession',
            name='score_details',
        ),
        migrations.CreateModel(
            name='SpeechScanSessionScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('practice_text_index', models.PositiveIntegerField(verbose_name='practice text index')),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0),
                                                                     django.core.validators.MaxValueValidator(1.0)],
                                            verbose_name='score')),
                ('word_scores', models.JSONField(blank=True, default=list,
                                                 help_text='list of word scores with their status and timing information',
                                                 verbose_name='word scores')),
                ('audio_file',
                 models.FileField(blank=True, null=True, upload_to='speech_scan_audio/', verbose_name='audio file')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('speech_scan_session',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_details',
                                   to='conversations.speechscansession', verbose_name='speech scan session')),
            ],
            options={
                'verbose_name': 'speech scan session score detail',
                'verbose_name_plural': 'speech scan session score details',
                'abstract': False,
            },
        ),
    ]
