# Generated by Django 4.2.15 on 2025-06-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conversations', '0008_remove_speechscansession_score_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='initial_texts',
            field=models.JSONField(blank=True, default=list,
                                   help_text='Initial texts to start the conversation, stored as a list of strings',
                                   verbose_name='initial text'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True,
                                   help_text='Description of the scenario. Used to provide context or instructions for the conversation in the prompt.',
                                   null=True, verbose_name='description'),
        ),
    ]
